### ISSUE TITLE
Transformer places `(net)` in KiCAD sexp which don't have nets assigned

### ISSUE THREAD

**Issue by mawildoer** [atopile/faebryk#13]
### Current Behaviour

The transformer will add `(net)` when there's no net assigned

<img width="1182" alt="Screenshot 2024-08-14 at 19 09 02" src="https://github.com/user-attachments/assets/d04df0ec-f622-41bd-bc1d-a332d6b3b058">

### Expected Behaviour

The net should be omitted if null

### Possible Solution

I believe the offending definition is here: https://github.com/atopile/faebryk/blob/39fbef66e01569c11b3a739950027e787e3b9e83/src/faebryk/libs/kicad/fileformats.py#L827

Perhaps there's a way to mark the field as "don't print me if I have no value"

### Version

3.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iopapamanoglou** [comment]
Fixed in #12
